#!/usr/bin/env python3
"""
Decodifica e instala o physics.wasm compilado.
Execute: python deploy_wasm.py
"""
import base64, os

B64 = (
    "AGFzbQEAAAABMAZgAABgA39/fQBgBX9/f399AGAIfX19fX19fX0Bf2AGfX19fX19AX9gBX9/fX19"
    "AAMHBgABAgMEBQQFAXABAQEFAwEAAgY/Cn8BQYCIBAt/AEGACAt/AEGACAt/AEGACAt/AEGAiAQL"
    "fwBBgAgLfwBBgIgEC38AQYCACAt/AEEAC38AQQELB5oCEQZtZW1vcnkCABFfX3dhc21fY2FsbF9j"
    "dG9ycwAAEHVwZGF0ZV9wYXJ0aWNsZXMAAQ5sZXJwX3Bvc2l0aW9ucwACEmNoZWNrX3JlY3Rfb3Zl"
    "cmxhcAADE2NoZWNrX3BvaW50X2luX3JlY3QABAtzbm93X3VwZGF0ZQAFGV9faW5kaXJlY3RfZnVu"
    "Y3Rpb25fdGFibGUBAAxfX2Rzb19oYW5kbGUDAQpfX2RhdGFfZW5kAwILX19zdGFja19sb3cDAwxf"
    "X3N0YWNrX2hpZ2gDBA1fX2dsb2JhbF9iYXNlAwULX19oZWFwX2Jhc2UDBgpfX2hlYXBfZW5kAwcN"
    "X19tZW1vcnlfYmFzZQMIDF9fdGFibGVfYmFzZQMJCqwGBgIAC8wCBQN9AX8BfQR/AX0CQCABQQFI"
    "DQAgAkMK16O7lEMAAIA/kiEDIAJDCtejvJRDAACAP5IhBCACQ83MTD2UIQUDQAJAAkAgAEEcaiIG"
    "KgIAIgdDAACAT10gB0MAAAAAYHFFDQAgB6khCAwBC0EAIQgLAkAgCEEBcUUNACAAIABBCGoiCSoC"
    "ACIA HIAKUIAAqAgCSOAIAIABBBGoiCiAAQQxqIgsqAgAiDCAClCAKKgIAkjgCAAJAIAhBAnFF"
    "DQAgCyAFIAySOAIACwJAIAhBBHFFDQAgCSAEIAeUOAIACyAAQRBqIgogCioCACAAQRRqKgIAIAKU"
    "kyIHOAIAIABBGGoiCUOamZk+IAMgCSoCAJQiDCAMQ5qZmT5dGzgCACAHQwAAAABfRQ0AIApBADYC"
    "ACAGIAhBfnGzOAIACyAAQSBqIQAgAUF/aiIBDQALCwv5AQIBfQV/AkAgA0EBSA0AQwAAgD9DAAAA"
    "AEMAAIA/IAQgBEMAAIA/XhsgBEMAAAAAXRsiBJMhBSADQQF0IgNBASADQQFKGyIDQQFxIQZBACEH"
    "AkAgA0EBRg0AIANB/v///wdxIQhBACEHIAIhAyABIQkgACEKA0AgAyAKKgIAIAWUIAQgCSoCAJSS"
    "OAIAIANBBGogCkEEaioCACAFlCAEIAlBBGoqAgCUkjgCACADQQhqIQMgCUEIaiEJIApBCGohCiAI"
    "IAdBAmoiB0cNAAsLIAZFDQAgAiAHQQJ0IgNqIAAgA2oqAgAgBZQgBCABIANqKgIAlJI4AgALCyUA"
    "IAEQA5IgBV4gACACkiAEXiAEIAaSIABecSAFIAeSIAFecXELHwAgAyAFkiABYCABIANgIAAgAmAg"
    "AiAEkiAAYHFxcQuXAQMBfQF/AX0CQCABQQFIDQADQCAAIABBDGoqAgAgACoCAJIiBTgCACAAQQRq"
    "IgYgAEEIaioCACAClCAGKgIAkiIHOAIAAkAgByAEXkUNACAGQYCAgIV8NgIAC0MAAAAAIQcCQAJA"
    "IAUgA14NACADIQcgBUMAAAAAXUUNAQsgACAHOAIACyAAQRRqIQAgAUF/aiIBDQALCwsA"
)

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "public", "wasm", "physics.wasm")
os.makedirs(os.path.dirname(out), exist_ok=True)

# Limpa espaços acidentais no base64
clean = B64.replace(" ", "").replace("\n", "")
with open(out, "wb") as f:
    f.write(base64.b64decode(clean))
print(f"✓ physics.wasm → {out} ({os.path.getsize(out)} bytes)")
