"""
gerar_wasm.py — Gera public/wasm/physics.wasm a partir do binário pré-compilado.

O binário abaixo (base64) foi compilado de physics.c com:
  clang --target=wasm32-unknown-unknown -O2 -nostdlib \
        -Wl,--no-entry -Wl,--export-all -Wl,--allow-undefined \
        -o physics.wasm physics.c

Uso:
  python gerar_wasm.py

Isso cria public/wasm/physics.wasm. Rode uma vez e pode apagar este script
(ou manter pra regenerar). O .wasm é o que o jogo realmente carrega.
"""
import base64
import os

WASM_B64 = "AGFzbQEAAAABMAZgAABgA39/fQBgBX9/f399AGAIfX19fX19fX0Bf2AGfX19fX19AX9gBX9/fX19AAMHBgABAgMEBQQFAXABAQEFAwEAAgY/Cn8BQYCIBAt/AEGACAt/AEGACAt/AEGACAt/AEGAiAQLfwBBgAgLfwBBgIgEC38AQYCACAt/AEEAC38AQQELB5oCEQZtZW1vcnkCABFfX3dhc21fY2FsbF9jdG9ycwAAEHVwZGF0ZV9wYXJ0aWNsZXMAAQ5sZXJwX3Bvc2l0aW9ucwACEmNoZWNrX3JlY3Rfb3ZlcmxhcAADE2NoZWNrX3BvaW50X2luX3JlY3QABAtzbm93X3VwZGF0ZQAFGV9faW5kaXJlY3RfZnVuY3Rpb25fdGFibGUBAAxfX2Rzb19oYW5kbGUDAQpfX2RhdGFfZW5kAwILX19zdGFja19sb3cDAwxfX3N0YWNrX2hpZ2gDBA1fX2dsb2JhbF9iYXNlAwULX19oZWFwX2Jhc2UDBgpfX2hlYXBfZW5kAwcNX19tZW1vcnlfYmFzZQMIDF9fdGFibGVfYmFzZQMJCqwGBgIAC8wCBQN9AX8BfQR/AX0CQCABQQFIDQAgAkMK16O7lEMAAIA/kiEDIAJDCtejvJRDAACAP5IhBCACQ83MTD2UIQUDQAJAAkAgAEEcaiIGKgIAIgdDAACAT10gB0MAAAAAYHFFDQAgB6khCAwBC0EAIQgLAkAgCEEBcUUNACAAIABBCGoiCSoCACIHIAKUIAAqAgCSOAIAIABBBGoiCiAAQQxqIgsqAgAiDCAClCAKKgIAkjgCAAJAIAhBAnFFDQAgCyAFIAySOAIACwJAIAhBBHFFDQAgCSAEIAeUOAIACyAAQRBqIgogCioCACAAQRRqKgIAIAKUkyIHOAIAIABBGGoiCUOamZk+IAMgCSoCAJQiDCAMQ5qZmT5dGzgCACAHQwAAAABfRQ0AIApBADYCACAGIAhBfnGzOAIACyAAQSBqIQAgAUF/aiIBDQALCwv5AQIBfQV/AkAgA0EBSA0AQwAAgD9DAAAAAEMAAIA/IAQgBEMAAIA/XhsgBEMAAAAAXRsiBJMhBSADQQF0IgNBASADQQFKGyIDQQFxIQZBACEHAkAgA0EBRg0AIANB/v///wdxIQhBACEHIAIhAyABIQkgACEKA0AgAyAKKgIAIAWUIAQgCSoCAJSSOAIAIANBBGogCkEEaioCACAFlCAEIAlBBGoqAgCUkjgCACADQQhqIQMgCUEIaiEJIApBCGohCiAIIAdBAmoiB0cNAAsLIAZFDQAgAiAHQQJ0IgNqIAAgA2oqAgAgBZQgBCABIANqKgIAlJI4AgALCyUAIAEgA5IgBV4gACACkiAEXiAEIAaSIABecSAFIAeSIAFecXELHwAgAyAFkiABYCABIANgIAAgAmAgAiAEkiAAYHFxcQuXAQMBfQF/AX0CQCABQQFIDQADQCAAIABBDGoqAgAgACoCAJIiBTgCACAAQQRqIgYgAEEIaioCACAClCAGKgIAkiIHOAIAAkAgByAEXkUNACAGQYCAgIV8NgIAC0MAAAAAIQcCQAJAIAUgA14NACADIQcgBUMAAAAAXUUNAQsgACAHOAIACyAAQRRqIQAgAUF/aiIBDQALCwsAlgEEbmFtZQANDHBoeXNpY3Mud2FzbQFsBgARX193YXNtX2NhbGxfY3RvcnMBEHVwZGF0ZV9wYXJ0aWNsZXMCDmxlcnBfcG9zaXRpb25zAxJjaGVja19yZWN0X292ZXJsYXAEE2NoZWNrX3BvaW50X2luX3JlY3QFC3Nub3dfdXBkYXRlBxIBAA9fX3N0YWNrX3BvaW50ZXIAOAlwcm9kdWNlcnMBDHByb2Nlc3NlZC1ieQEMVWJ1bnR1IGNsYW5nETE4LjEuMyAoMXVidW50dTEpACwPdGFyZ2V0X2ZlYXR1cmVzAisPbXV0YWJsZS1nbG9iYWxzKwhzaWduLWV4dA=="

def main():
    aqui = os.path.dirname(os.path.abspath(__file__))
    destino = os.path.join(aqui, "physics.wasm")
    with open(destino, "wb") as f:
        f.write(base64.b64decode(WASM_B64))
    tamanho = os.path.getsize(destino)
    print(f"OK -> {destino} ({tamanho} bytes)")
    print("Recarregue o jogo. No console (F2 ou DevTools) deve aparecer:")
    print("  [WASM] physics.wasm carregado")

if __name__ == "__main__":
    main()
